### ISSUE TITLE
Should we track users that aren't in the room?

### ISSUE THREAD

**Issue by ArcticEcho** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#101]
Last night, [it was brought to my attention](http://chat.stackoverflow.com/transcript/message/26602105#26602105) that Closey will still track users even if they're not in the room. Which we may (or may not) want to do, thoughts?

**Comment by Unihedro** [comment]
Yes would be my vote. Freehand ftw.

**Comment by gunr2171** [comment]
This is being added to the v2 spec.

**Comment by gunr2171** [comment]
Proposal: the bot will track users who are registered whether they are in the room or not, but the bot will only ping them if they are in the room when they are to be pinged.

**Comment by ArcticEcho** [comment]
For now, I've just removed the ping from messages (we still post all the usual stuff, passed audits, reviewing started, etc,).
