### ISSUE TITLE
Bot should make a best guess at a command

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#111]
Suppose someone types 

> @ Closey alve

The bot will just respond with "don't know what you mean."

The bot should first compare what the user said against the list of current commands. If it is close (% is configurable) then the bot will reply "did you mean [x]".

If it's above this threshold, the bot will ignore it.

This feature needs to be written into the spec as well as developed.

**Comment by ArcticEcho** [comment]
Any idea on the %? Currently we're using 50% for Nor.

**Comment by ArcticEcho** [comment]
Ok, So there's a few edge cases currently where the code will get things wrong and suggest a command with wrong options.

Side note: it's still passing the old incomingMessage object to the action to be ran if the user replies with "yes". We should change this ofc to the suggested text from the SimilarCommand class.
