### ISSUE TITLE
Duplicate Key value insertion problem

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#127]
Got some people to help test Closey just now, and we ran into a problem in the `SaveReview` method.

![2016-02-04 20_49_54-calendar](https://cloud.githubusercontent.com/assets/8290105/12835889/dd296e2e-cb81-11e5-83c0-0a8ef7a800ff.png)

![2016-02-04 20_50_19-phone companion](https://cloud.githubusercontent.com/assets/8290105/12835896/f0549d2a-cb81-11e5-81dd-8b0c8e447e21.png)

Yes, yes, this is an image of an error and code. No, I don't care.

I'll do some more investigation on this later, but I have a feeling it's because of that "this method gets called twice" that I've been noticing.

[Context can be found here](http://chat.stackoverflow.com/transcript/message/28579070#28579070).

**Comment by ArcticEcho** [comment]
I thought we fixed this bug a few days back. Take a closer look at:

    var res = rev.Results.First();
