### ISSUE TITLE
Update the Wiki

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#128]
The Wiki for the bot is/is going to be _super_ out of date. All the pages need to be updated.

I can do this or someone else can pick it up.

**Comment by ArcticEcho** [comment]
I'll make a start; not sure if I'll finish it all off though.

**Comment by ArcticEcho** [comment]
Updated the wiki home page. `[review-pls]`.

**Comment by gunr2171** [comment]
Updated the installation page. We're done here.
