### ISSUE TITLE
Ensure opted-out users are not tracked

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#131]
Go over the code and exclude any opted-out users from review tracking.

**Comment by ArcticEcho** [comment]
I've already accounted for opted-out users in the user tracking class. The reviewer commands haven't been touched though.

**Comment by gunr2171** [comment]
The commands that require the Reviewer group won't care about the opt-in-out value, so we don't need to worry about those.

I'll close this.
