### ISSUE TITLE
Respect the username when Closey reports a passed audit

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#148]
When Close says 

> [Username]  passed an [tag] audit 

for some reason it mangles the username.

Like _Rao passed an ios audit!_ or _Rene passed an haskell audit_

My name isn't capitalized nor is Rao the correct name for Bhargav Rao

**Comment by Bhargav-Rao** [comment]
An example can be seen in this [report](http://chat.stackoverflow.com/transcript/message/29296401#29296401)
