### ISSUE TITLE
Add commands to get tags

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#15]
The following commands need to get added:

- current tag
- next x tags
- start event

Details on those commands are int the setup.md file.

Most of the work is in the sede branch.

**Comment by gunr2171** [comment]
Alright, I need help finishing this one. Rene made the SEDEAccessor class for me, but I get errors when running it a second item, and it currently does not build because of class inaccessibility.

Also, I flat-out don't understand the code. Not going to lie here.

What I have so far is on the `issue-15` branch. You can find the main file at `/CVChatbot/CVChatbot.Bot/SEDEAccessor.cs`.

**Comment by rschrieken** [comment]
current tag is done in my first commit

**Comment by ArcticEcho** [comment]
I'll add a cache + refactor.

**Comment by ArcticEcho** [comment]
Caching + partial refactoring done in [83579dcb01](https://github.com/SO-Close-Vote-Reviewers/SOCVR-Chatbot/commit/83579dcb0191984ecb6a07ba133cc828b78c062a).
