### ISSUE TITLE
And then they changed the max number of close vote review items....

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#153]
http://meta.stackoverflow.com/questions/319131/1-2-3-test-let-s-increase-the-number-of-reviews-close-vote-for-science

>Over the next 30 days, we'll increase the number of reviews per day and max close votes to the following:

> * When the queue size is less than 1000, the max reviews per day is 30
> * When the queue size is 1000 or more, the max reviews per day is 60
> * Maximum close votes = 60 to correspond to the new max reviews per day

The bot pings you when you complete 40 items, then pings you once for each review you make past that.

http://chat.stackoverflow.com/transcript/message/29380928#29380928

**Comment by ArcticEcho** [comment]
Fixed in [3.2.3](https://github.com/SO-Close-Vote-Reviewers/SOCVR.Net/commit/610ae72509717892a76bcccdf9b24a336e733381) of SOCVR.Net.
