### ISSUE TITLE
Shouldn't we use the database for the source of all data for stats?

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#162]
The `My Stats` commands starts with the following:

    var tracker = (UserTracking)typeof(Program).GetField("watcher", BindingFlags.NonPublic | BindingFlags.Static).GetValue(null);
    var msg = new MessageBuilder();
    var currentDate = DateTimeOffset.UtcNow;
    var revCount = tracker.WatchedUsers[incomingChatMessage.Author.ID].CompletedReviewsCount;

    var reviews = db.ReviewedItems
        .Where(x => x.ReviewerId == incomingChatMessage.Author.ID)
        .Where(x => x.ReviewedOn.Date == currentDate.Date)
        .ToList();

    msg.AppendText($"You've reviewed {revCount} post{(revCount == 1 ? "" : "s")} today");

This means that we use the `UserTracking` class for the main number of reviews, but the database for the actual entries (audits and table).

![image](https://cloud.githubusercontent.com/assets/8290105/15619872/f7854c9c-2424-11e6-86ee-2d29c9ec26e9.png)

I really think all of this information should be in one place: the database. If you want the number of audits you go to the database to query it.

    var audits = db.ReviewedItems
        .Where(x => x.ReviewerId == incomingChatMessage.Author.ID)
        .Where(x => x.ReviewedOn.Date == currentDate.Date)
        .Where(x => x.AuditPassed != null)
        .ToList();

As long as we have two different sources of data, we are going to run into instances like [this][1]:

> You've reviewed 0 posts today. The time between your first and last review today was 17 minutes and 29 seconds, averaging to a review every 5 minutes and 49 seconds.

![image](https://cloud.githubusercontent.com/assets/8290105/15619882/10964ae2-2425-11e6-836e-fa4efa5440d6.png)

Now, I know about deleted audits. If that's the case, then we still need to record it, even if we don't have all the information about it. I can make changes to the database so that the information that we don't have is not required.

@ArcticEcho what do you think about this? I would much rather have a system that says "if you want information, go ask the database."

 [1]: http://chat.stackoverflow.com/transcript/message/30815723#30815723

**Comment by ArcticEcho** [comment]
> Now, I know about deleted audits. If that's the case, then we still need to record it [...]

Sounds good. The only reason why I decided to consult the `UserTracker` in the first place was due to delete audits.

**Comment by gunr2171** [comment]
I made issues #163, #164, and #165 to cover the parts of this process.
