### ISSUE TITLE
The tags should  link to filter the queue

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#166]
example ```http://stackoverflow.com/review/close?filter-tags=string```

I do realize this will break tag layout so don't move the cheese before all mice know where it is going

**Comment by gunr2171** [comment]
right now tags are in `[tag:tag-name]` format, and the markdown automatically makes them links.

How about this:

[test-tag](http://stackoverflow.com/review/close?filter-tags=string)

    [test-tag](http://stackoverflow.com/review/close?filter-tags=string)
