### ISSUE TITLE
If any message fails to post throw an exception

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#23]
The bot just sends out a message to post and does not check if it was successful. The bot should throw an exception if the posting of a message fails.

I need to check with @ArcticEcho to determine how `PostMessage` and  `PostReply` indicate a failed posting. It is either a `null` return value or the methods themselves throw an exception.

I should also make myself an extension method `PostMessageOrThrow` which will throw the exception for me on posting failure.

**Comment by ArcticEcho** [comment]
Chat methods will *not* throw an exception (unless something goes catastrophically wrong). But rather will return `null`/`false`.

**Comment by gunr2171** [comment]
Great, makes my life easier. Tonight I'll commit everything that finishes beta-2 then this is next on the list.
