### ISSUE TITLE
Triggers with not exactly one space after ">" are not recognised by bot

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#40]
Sometimes when you are copy/pasting in a message and you blockquote it you may have an extra space(s) between the `>` and your message. For example:

    >  This is my message

Chat will handle it fine. Even the markdown here on Github likes it (and trims out the spaces at the front)

>  This is my message

The bot's regex patterns for any command that allows the message to be blockquote needs to allow for multiple spaces after the `>` key.

Assigning this to @ProgramFOX  because he already has this done and just needs to PR it.

**Comment by gunr2171** [comment]
@ArcticEcho also suggested `^>? *` as the start of the matching pattern.

**Comment by ProgramFOX** [comment]
PR #41 merged on dev branch.

**Comment by gunr2171** [comment]
So, I've been thinking this one over for a bit. There is one dangerous situation that can happen because of `^>? *` or `^(?:> *)?`.

Say you write the following message, with no space after the `>`.

    >This is my message

And they you say "oh shoot, the obviously didn't blockquote, let me fix that".

> This is my message

Problem is now the bot has picked it up twice. This is even worse for triggers that don't give any feedback.

My original regex was `^(?:> )?`, which said "if there is a `>` then it must be followed by exactly one space".

I really think the correct way to fix this, and avoid the above situation, is to use `^(?:> +)?`, which allows _one_ or more spaces after the `>`, and only if it is present.
