### ISSUE TITLE
Remove Entity Framework

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#44]
EF is good and all, but it will be much harder to use it once (and if) I convert to another database type.

There are also other reasons (go look at the pre-build events for the UI project).

The goal for this task is to completely remove EF from the project and use pure sql statements (and functions) to gather and transfer data.

**Comment by gunr2171** [comment]
Most of the work has been done now. Everything is in the no-ef branch.

**Comment by Vincentyification** [comment]
Aweshume! This is a good idea.
