### ISSUE TITLE
Show me which tags I have completed

### ISSUE THREAD

**Issue by ProgramFOX** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#52]
I don't remember all tags I've cleared, so it would be nice if there's a command `my completed tags` to make the bot tell me which tags I've cleared.

**Comment by Vincentyification** [comment]
+1, this can be an arbitrary map of values, but will be handy to have!

**Comment by gunr2171** [comment]
I'll work on this today, should be very easy.

**Comment by Vincentyification** [comment]
Famous last words...
