### ISSUE TITLE
Parsing of the html from SEDE never ends

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#72]
The CQ.Create call to parse the first html result in the GetTags method never returns and seem to be looping inside the CQ lib on CsQuery.HtmlParser.CsQueryTreeBuilder.AppendCharacters

**Comment by rschrieken** [comment]
branch with a possible fix https://github.com/SO-Close-Vote-Reviewers/SOCVR-Chatbot/tree/issue-72

**Comment by gunr2171** [comment]
I'll check it out now and see if it works.

**Comment by rschrieken** [comment]
If this doesn't work reliably I'll do some parsing my self ...

**Comment by gunr2171** [comment]
Well, it worked, but it took 3 minutes

http://chat.stackoverflow.com/transcript/message/21804626#21804626

I'll go test the master branch to see if it's the same.

**Comment by gunr2171** [comment]
Tried master branch, no dice :(

**Comment by ArcticEcho** [comment]
I've just gone over the `GetSedeQueryCsvRevisionId` method again, and it appears we don't even need to use CsQuery. So I've created a new branch and pull request (#73) removing its usage.
