### ISSUE TITLE
Logic inconsistency when sessions are missed

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#77]
Kevin Brown had an odd occurrence happen in chat the other day: http://chat.stackoverflow.com/transcript/message/22150976#22150976

A week ago he [started a session](http://chat.stackoverflow.com/transcript/41570?m=21994377#21994377) but never finished. Now he competed a session, but when he went to see the stats the bot thought that he was [still in the middle of a session](http://chat.stackoverflow.com/transcript/message/22151373#22151373).

The intended thought for the warning was "here are your stats from last session, which happens to be in the past (like yesterday). By the way, you are in the middle of a session _right now_, just to let you know".

The problem is that the "session right now", which was the uncompleted session, happened _before_ the newly completed session.

So, I need to think about how I want to fix this one.

**Comment by gunr2171** [comment]
I think I've got a good way to solve this. When you run the `starting` command, and that user has _any_ open sessions, the bot will close those sessions (add 1 minute to start time) and add the following to the response:

> **Note:** You previously had an open session. I have forcefully closed it.

**Comment by Vincentyification** [comment]
Eh, maybe the bot could poke a user after a while of `starting` in case they've forgotten.

> Hey @gunr2171, you haven't reported in an hour. Did you only forget or should we send a search team?

**Comment by gunr2171** [comment]
Good idea, and I'd love to do that, but I can't until the bot can run an action without a human starting it (like on a schedule).
