### ISSUE TITLE
Poke to see if users are still alive after starting a session for so long.

### ISSUE THREAD

**Issue by Unihedro** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#79]
The bot could poke a user after a while of starting in case they've forgotten.

> Hey @gunr2171, you haven't reported in an hour. Did you only forget or should we send a search team?

From #77

**Comment by gunr2171** [comment]
Version 2 of the program will only ping a user about reviewing when:

1. The bot detects the first cvq review of a UTC day
2. The user hits 40 cvq reviews

This means that we don't care if a user makes a few reviews and goes away. We will also not ping a user at midnight about their "session" that ended with a few reviews.
