### ISSUE TITLE
More "alive" responses

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#82]
Tyler wants more Monty Python quotes for responses to the "alive" command.

I want that too, because reasons.

Soon someone will come up with a list of things to add.

**Comment by Tyler-H** [comment]
"I feel happy"
"I'm not dead yet" <-- Already in, I think
"I think I'll go for a walk"
"I don't want to go on the cart"
"I feel fine"
