### ISSUE TITLE
As a voter I want all my statistics also available when Closey runs on Linux

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#90]
Reminder to Export and import data from the windows sql-server box to the new linux box

**Comment by gunr2171** [comment]
I'm making the repository right now:

https://github.com/SO-Close-Vote-Reviewers/SOCVR-Chatbot-Importer

**Comment by gunr2171** [comment]
User listing, audits, and completed tags have been imported.
Will do the rest tomorrow night or weekend.

**Comment by gunr2171** [comment]
Due to bugs with version 1 code, we are not going to be able to migrate the data from version 1 to version 2.
