### ISSUE TITLE
Ping only reviewers that are pingable

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#92]
implement  http://chat.stackoverflow.com/rooms/pingable/41570 to get the list of users that are pingable and only ping those
or show a warning for users that are not pingable anymore

find a resultset [here](https://gist.github.com/rschrieken/9caf23111cc503209e87)

**Comment by ArcticEcho** [comment]
This issue has now migrated to [ChatExchange.Net #14](https://github.com/ArcticEcho/ChatExchange.Net/issues/14).
