### ISSUE TITLE
Have a triggers command

### ISSUE THREAD

**Issue by rschrieken** [SO-Close-Vote-Reviewers/SOCVR-Chatbot#94]
Have a triggers command that explains what triggers are/ list triggers and how they work in conjunction with commands.

**Comment by gunr2171** [comment]
While we're at it, the "help" command should also mention "triggers"

> This is a chatbot for the SO Close Vote Reviewers chat room developed by its members. For more information see the github page. Reply with `commands` to see a list of commands or `triggers` for the list of triggers.

As for the output of the `triggers` command, that will most likely be a copy of the [wiki page](https://github.com/SO-Close-Vote-Reviewers/SOCVR-Chatbot/wiki/Triggers).

**Comment by ArcticEcho** [comment]
Triggers are no longer in use in V2.
